name: Test Workflow
on:
  pull_request:
    types: [opened, edited]
jobs:
  handle-trello-card:
    name: Handle trello card
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.body, 'https://trello.com/c/') }}
    steps:
      - run: TICKET_ID=echo '${{ github.event.pull_request.body }}' | grep -o 'https://trello.com/c/.*/' test.md | awk -F '/' '{ print $5 }'
      - run: echo $TICKET_ID
      
    
