name: Test Workflow
on:
  pull_request:
    types: [opened, edited]
jobs:
  handle-trello-card:
    name: Handle trello card
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.body, 'https://trello.com/c/') }}
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
      PENDING_ID: 66b3b45f4e93731595994bb2
      API_AUTH: "key=83f6f0494e8f3790e73f592fcc6d073b&token=ATTA8a1bd95c7b80088ac5fb2add5fa8d5c5dfeb232a703f36fac8d0a6683accedb7A78C190F"
    steps:
      - run: |
          TICKET_ID=$(echo "$PR_BODY" | grep -o 'https://trello.com/c/.*/' | awk -F '/' '{ print $5 }')
          curl -XPUT "https://api.trello.com/1/cards/$TICKET_ID?idList=$PENDING_ID&$API_AUTH"
      
    
