name: Merge PR Workflow
on:
  pull_request_target:
    types: [closed]
jobs:
  handle-trello-card:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Handle Trello Card
        if: ${{ contains(github.event.pull_request.body, 'https://trello.com/c/') }}
        env:
          VALIDATED_ID: 66b3b5daa8bd7eb9cbaa8e91
          API_AUTH: "key=83f6f0494e8f3790e73f592fcc6d073b&token=ATTA8a1bd95c7b80088ac5fb2add5fa8d5c5dfeb232a703f36fac8d0a6683accedb7A78C190F"
        run: |
          TICKET_ID=$(echo "${{ github.event.pull_request.body }}" | grep -o 'https://trello.com/c/.*/' | awk -F '/' '{ print $5 }')
          curl -XPUT "https://api.trello.com/1/cards/$TICKET_ID?idList=$VALIDATED_ID&$API_AUTH"
      
    
