name: Open PR Workflow
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, review_requested]
jobs:
  handle-pr-open:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Update Trello Card
        if: ${{ contains(github.event.pull_request.body, 'https://trello.com/c/') }}
        env:
          PENDING_ID: 66b3b45f4e93731595994bb2
          API_AUTH: "key=83f6f0494e8f3790e73f592fcc6d073b&token=ATTA8a1bd95c7b80088ac5fb2add5fa8d5c5dfeb232a703f36fac8d0a6683accedb7A78C190F"
        run: |
          TICKET_ID=$(echo "${{ github.event.pull_request.body }}" | grep -o 'https://trello.com/c/.*/' | awk -F '/' '{ print $5 }')
          curl -XPUT "https://api.trello.com/1/cards/$TICKET_ID?idList=$PENDING_ID&$API_AUTH"
          HAS_LINK=$(curl "https://api.trello.com/1/cards/$TICKET_ID/attachments?fields=url&$API_AUTH" | grep "${{ github.event.pull_request.url }}")
          if [ -z "$HAS_LINK" ]; then
            curl -XPOST "https://api.trello.com/1/cards/$TICKET_ID/attachments?url=${{ github.event.pull_request.url }}&$API_AUTH"
          fi
      - name: Update Github PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label 'Needs Review'
