name: Open PR Workflow
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, review_requested]
jobs:
  handle-pr-open:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Update Github PR
        env:
          IS_APPS: ${{ contains(vars.MAIN_TEAM, github.actor) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          if [[ $IS_APPS == true ]]; then TEAM_LABEL='Apps'; else TEAM_LABEL='Platform'; fi
          gh pr edit ${{ github.event.pull_request.number }} --add-label $TEAM_LABEL --add-label 'Needs Review' --remove-label 'Needs Work'

