name: Reject PR Workflow
on:
  pull_request_review_comment:
    types: [created, deleted]
jobs:
  handle-pr-rejected:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo 'abc'
