name: Reject PR Workflow
on:
  pull_request_target:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]
jobs:
  handle-pr-rejected:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo 'abc'
