name: Reject PR Workflow
on:
  pull_request_review:
    types: [submited, edited, dismissed]
jobs:
  handle-pr-rejected:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo 'abc'
