name: Reject PR Workflow
on:
  pull_request_review:
    types: [submitted]
env:
  SPRINT_ID: 66b3b45fbd7dc7a831b372d0
  API_AUTH: "key=83f6f0494e8f3790e73f592fcc6d073b&token=ATTA8a1bd95c7b80088ac5fb2add5fa8d5c5dfeb232a703f36fac8d0a6683accedb7A78C190F"
jobs:
  handle-trello-card:
    if: ${{ contains(github.event.pull_request.body, 'https://trello.com/c/') && github.event.review.state == 'changes_requested' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          TICKET_ID=$(echo "${{ github.event.pull_request.body }}" | grep -o 'https://trello.com/c/.*/' | awk -F '/' '{ print $5 }')
          curl -XPUT "https://api.trello.com/1/cards/$TICKET_ID?idList=$SPRINT_ID&$API_AUTH"
      
    
